let mapleader = ','

syntax on
set nocompatible
set tabstop=3
set number
set relativenumber
set autoindent
set wildmenu
set hidden
set splitbelow splitright
set ignorecase
set smartcase

" no more swp files!
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile

"exucute root dir vimrc
set exrc
" Refresh buffer
set autoread


call plug#begin()

Plug 'dart-lang/dart-vim-plugin'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'neoclide/jsonc.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdtree'
Plug 'vim-scripts/Rainbow-Parenthesis'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'zchee/vim-flatbuffers'
Plug 'fatih/vim-go'
Plug 'crusoexia/vim-monokai'
Plug 'lervag/vimtex'
Plug 'editorconfig/editorconfig-vim'
Plug 'posva/vim-vue'
Plug 'plasticboy/vim-markdown'

call plug#end()

let NERDTreeShowHidden=1

let g:airline_theme='term'

" Latex config
let g:tex_flavor='latex'
let g:vimtex_compiler_progname = 'nvr'
" let g:vimtex_view_general_viewer = 'open -a /Applications/Skim.app'
" let g:vimtex_view_skim_activate = 1
let g:vimtex_view_method = 'skim'


colorscheme monokai

let g:fzf_layout = { 'window': { 'width': 0.8, 'height': 0.8 } }
let $FZF_DEFAULT_OPTS='--reverse'
let g:fzf_default_command='fd --type f -H --exclude .git --exclude "*.png" --exclude "*.ttf"'
let $FZF_DEFAULT_COMMAND=g:fzf_default_command


" Enable mouse support
set mouse=a

" Always keep 10 lines below/above cursor
set scrolloff=10

